<?php

namespace Database\Seeders;

use App\Models\InvoiceTemplate;
use Illuminate\Database\Seeder;

class InvoiceTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // Core Free Templates (1-4)
            [
                'slug' => 'minimalist',
                'name' => 'Modern Minimalist',
                'description' => 'Light, clean, and spacious typography with subtle dividers. Perfect for freelancers, consultants, and creators.',
                'category' => 'Minimalist',
                'price' => 0.00,
                'is_free' => true,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'corporate',
                'name' => 'Corporate Classic',
                'description' => 'Authoritative deep navy banner with formal serif accents and structured table borders for established enterprises.',
                'category' => 'Corporate',
                'price' => 0.00,
                'is_free' => true,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'creative',
                'name' => 'Creative Studio',
                'description' => 'Vibrant violet accent card, asymmetric metadata layout, and rounded totals box tailored for design and marketing agencies.',
                'category' => 'Creative',
                'price' => 0.00,
                'is_free' => true,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'grid',
                'name' => 'Clean Grid',
                'description' => 'Crisp 1px slate grid cells with strict tabular ledger alignment. Ideal for accounting, bookkeeping, and finance.',
                'category' => 'Minimalist',
                'price' => 0.00,
                'is_free' => true,
                'is_active' => true,
                'sort_order' => 4,
            ],

            // Premium Modern Templates (5-25)
            [
                'slug' => 'executive_dark',
                'name' => 'Executive Slate',
                'description' => 'Charcoal slate header with luxury brass accents and formal styling for legal, finance, and premium consulting.',
                'category' => 'Corporate',
                'price' => 9.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'modern_tech',
                'name' => 'Modern Tech & SaaS',
                'description' => 'Electric cyan & emerald terminal accents with monospace metadata badges. Built for software developers, IT firms, and SaaS.',
                'category' => 'Tech & SaaS',
                'price' => 9.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'swiss_clean',
                'name' => 'Swiss International',
                'description' => 'Bold asymmetrical typography, stark red accent, and ultra-high contrast based on iconic modernist Swiss graphic design.',
                'category' => 'Minimalist',
                'price' => 9.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'slug' => 'tokyo_compact',
                'name' => 'Tokyo High-Density',
                'description' => 'Ultra space-efficient compact ledger designed specifically for 15+ line items with dual-column subtotal summary.',
                'category' => 'Specialty',
                'price' => 9.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'slug' => 'london_classic',
                'name' => 'London Bespoke',
                'description' => 'Centered traditional crest header, elegant serif typography, and double pinstripe framing for bespoke luxury services.',
                'category' => 'Corporate',
                'price' => 9.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'slug' => 'berlin_mono',
                'name' => 'Berlin Industrial',
                'description' => 'Monospaced typewriter font, architectural wireframe borders, and stamp-like status badge for makers and architects.',
                'category' => 'Creative',
                'price' => 9.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'slug' => 'studio_bold',
                'name' => 'Dynamic Agency',
                'description' => 'Giant invoice number watermark, high-contrast black & amber highlight bar, and standout designer layout.',
                'category' => 'Creative',
                'price' => 12.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'slug' => 'healthcare_pro',
                'name' => 'Medical & Healthcare',
                'description' => 'Calming clinical teal palette with dedicated patient/provider reference blocks and sanitary clean lines.',
                'category' => 'Industry',
                'price' => 9.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'slug' => 'retail_tax',
                'name' => 'Retail & Trade Tax',
                'description' => 'Detailed multi-tier tax breakdown table, cashier-style barcode badge, and strict regulatory tax receipt layout.',
                'category' => 'Industry',
                'price' => 9.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'slug' => 'consulting_sleek',
                'name' => 'Strategic Consulting',
                'description' => 'Deep royal indigo header, dual-column executive brief layout, and refined financial presentation styling.',
                'category' => 'Corporate',
                'price' => 12.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'slug' => 'construction_heavy',
                'name' => 'Contractor & Trades',
                'description' => 'Industrial amber & black hazard badge, structured materials vs labor breakdown, and job site reference fields.',
                'category' => 'Industry',
                'price' => 9.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'slug' => 'legal_formal',
                'name' => 'Legal & Judiciary',
                'description' => 'Traditional legal seal graphic, roman serif typography, and expansive liability disclaimer & retainer notes block.',
                'category' => 'Corporate',
                'price' => 12.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'slug' => 'gradient_flow',
                'name' => 'Neon Gradient',
                'description' => 'Smooth violet-to-blue modern gradient banner with pill-shaped quantity badges and contemporary agency flair.',
                'category' => 'Creative',
                'price' => 9.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'slug' => 'crypto_dark',
                'name' => 'Fintech Dark Mode',
                'description' => 'Complete dark mode palette with dedicated crypto wallet address box, bank transfer IBAN block, and modern tech styling.',
                'category' => 'Tech & SaaS',
                'price' => 12.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'slug' => 'vintage_craft',
                'name' => 'Artisan & Vintage',
                'description' => 'Warm sepia tones, retro dotted borders, and handcrafted organic badge for artisan shops, bakeries, and boutiques.',
                'category' => 'Creative',
                'price' => 9.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 19,
            ],
            [
                'slug' => 'nordic_frost',
                'name' => 'Nordic Minimal',
                'description' => 'Cool ice blue highlights, soft muted grays, and Scandinavian functional aesthetic with balanced negative space.',
                'category' => 'Minimalist',
                'price' => 9.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'slug' => 'horizon_split',
                'name' => 'Split Dual-Tone',
                'description' => 'Left vertical dark accent sidebar for client & invoice metadata with right-hand spacious line items canvas.',
                'category' => 'Creative',
                'price' => 12.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'slug' => 'metro_blocks',
                'name' => 'Metro Geometry',
                'description' => 'Colorful category block tags, card-based subtotal modules, and geometric tile hierarchy for digital products.',
                'category' => 'Specialty',
                'price' => 9.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 22,
            ],
            [
                'slug' => 'zen_whitespace',
                'name' => 'Zen Serenity',
                'description' => 'Soft sage green & stone palette with delicate hairline rules and mindful Japanese aesthetic balance.',
                'category' => 'Minimalist',
                'price' => 9.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 23,
            ],
            [
                'slug' => 'aurora_glow',
                'name' => 'Aurora Twilight',
                'description' => 'Radiant dusk-to-dawn accent border glow with modern pill tags for multimedia production studios and animators.',
                'category' => 'Creative',
                'price' => 12.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 24,
            ],
            [
                'slug' => 'architect_lines',
                'name' => 'Architect Blueprint',
                'description' => 'Subtle engineering grid background with precision dimension markers and blueprint cyan technical aesthetic.',
                'category' => 'Industry',
                'price' => 12.00,
                'is_free' => false,
                'is_active' => true,
                'sort_order' => 25,
            ],
        ];

        foreach ($templates as $data) {
            InvoiceTemplate::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
